### ISSUE TITLE
Crashes when `:watch-paths` contains a non-existent path.

### ISSUE THREAD

**Issue by wildwestrom** [nextjournal/clerk#12]
I'm gonna look at this later and see if I can make this fail more gracefully.

```clj
(clerk/serve! {:watch-paths ["src" "notebooks"]
               :browse? true})
               ;; "notebooks" doesn't exist.
```

## Stacktrace
```
Clerk webserver started on 7777...
Starting new watcher for paths ["src" "notebooks"]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" Syntax error compiling at (user.clj:4:1).
	at clojure.lang.Compiler.load(Compiler.java:7652)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:368)
	at clojure.lang.RT.maybeLoadResourceScript(RT.java:364)
	at clojure.lang.RT.doInit(RT.java:486)
	at clojure.lang.RT.init(RT.java:467)
	at clojure.main.main(main.java:38)
Caused by: java.nio.file.NoSuchFileException: notebooks
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2717)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
	at io.methvin.watcher.PathUtils.recursiveVisitFiles(PathUtils.java:108)
	at io.methvin.watcher.PathUtils.initWatcherState(PathUtils.java:78)
	at io.methvin.watcher.DirectoryWatcher.<init>(DirectoryWatcher.java:190)
	at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:122)
	at nextjournal.beholder$create.invokeStatic(beholder.clj:29)
	at nextjournal.beholder$create.invoke(beholder.clj:20)
	at nextjournal.beholder$watch.invokeStatic(beholder.clj:37)
	at nextjournal.beholder$watch.doInvoke(beholder.clj:31)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at nextjournal.clerk$serve_BANG_.invokeStatic(clerk.clj:266)
	at nextjournal.clerk$serve_BANG_.invoke(clerk.clj:243)
	at user$eval12465.invokeStatic(user.clj:11)
	at user$eval12465.invoke(user.clj:11)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	... 6 more
```

**Comment by mk** [comment]
I leaning towards failing here is better than the alternative of swallowing the error (and possibly just logging it?). A path does need to exist after all in order to be watchable. I think this early failing is preferred. Consider making a typo in your `:watch-paths`, then Clerk would swallow it and a user will get confused as to why changes aren't picked up.

The error message also seems to give a decent hint to where the problem lies. Feel free to reopen with a suggestion for something actionable.

**Comment by fuadsaud** [comment]
Has this behavior changed?

I hit this problem when passing both an existing and non-existent paths to `:watch-paths` and it didn't throw, but also make watch not work (it didn't refresh the page on change).
