### ISSUE TITLE
Commit not found for io.github.nextjournal/dejavu

### ISSUE THREAD

**Issue by rgkirch** [nextjournal/clerk#213]
I'm on windows. I just downloaded bb [v0.9.162](https://github.com/babashka/babashka/releases/tag/v0.9.162).

```
➜  clerk git:(main) bb dev :browse\? true

Clojure tools not yet in expected location: C:\Users\richie\.deps.clj\1.11.1.1155\ClojureTools\clojure-tools-1.11.1.1155.jar
Downloading https://download.clojure.org/install/clojure-tools-1.11.1.1155.zip to C:\Users\richie\.deps.clj\1.11.1.1155\ClojureTools
Successfully installed clojure tools!
Cloning: https://github.com/nextjournal/dejavu.git
Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5
➜  clerk git:(main) bb dev :browse\? true

Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5

```

**Comment by mk** [comment]
Strange, the commit should be there, see https://github.com/nextjournal/dejavu/commit/3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5

@borkdude do you have an idea what could be causing this?

**Comment by borkdude** [comment]
I can't reproduce in Powershell. To be sure, I deleted `c:\Users\borkdude\.deps.clj` and `c:\Users\borkdude\.gitlibs`:

<img width="1389" alt="Screenshot 2022-09-08 at 17 34 34" src="https://user-images.githubusercontent.com/284934/189164556-81e02e95-9294-4f53-bcef-7c8208ea128e.png">

Will also try cmd.exe.

**Comment by rgkirch** [comment]
I deleted `c:\Users\me\.clojure` and then ran these commands. I didn't find a `.cpcache` folder.

powershell
```
PS C:\Users\richie> cd .\notMyCode\nextjournal\clerk\
PS C:\Users\richie\notMyCode\nextjournal\clerk> bb dev :browse\? true
Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5
PS C:\Users\richie\notMyCode\nextjournal\clerk> bb --version
Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5
PS C:\Users\richie\notMyCode\nextjournal\clerk> bb
Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5
PS C:\Users\richie\notMyCode\nextjournal\clerk> cd ..
PS C:\Users\richie\notMyCode\nextjournal> bb --version
babashka v0.9.162
PS C:\Users\richie\notMyCode\nextjournal> git --version
git version 2.37.1
```
cmd
```
C:\Users\richie\notMyCode\nextjournal\clerk>ls -a
.               .git          LICENSE    book.clj    deps.edn   package.json     test
..              .github       README.md  build.clj   dev        resources        tests.edn
.clj-kondo      .gitignore    bb         chinook.db  index.clj  shadow-cljs.edn  ui_tests
.dir-locals.el  CHANGELOG.md  bb.edn     clerk.el    notebooks  src
```

```
C:\Users\richie\notMyCode\nextjournal\clerk>bb
Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5
```

**Comment by rgkirch** [comment]
Sorry, I see you deleted two additional folders.
I tried again after deleting `C:\Users\richie\.deps.clj`, `C:\Users\richie\.gitlibs`, and `C:\Users\richie\.clojure`.

```
PS C:\Users\richie\notMyCode\nextjournal\clerk> bb
Clojure tools not yet in expected location: C:\Users\richie\.deps.clj\1.11.1.1155\ClojureTools\clojure-tools-1.11.1.1155.jar
Downloading https://download.clojure.org/install/clojure-tools-1.11.1.1155.zip to C:\Users\richie\.deps.clj\1.11.1.1155\ClojureTools
Successfully installed clojure tools!
Cloning: https://github.com/nextjournal/dejavu.git
Error building classpath. Commit not found for io.github.nextjournal/dejavu in repo https://github.com/nextjournal/dejavu.git at 3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5
```

**Comment by borkdude** [comment]
@rgkirch I ran `bb print-deps` and it prints this deps map. Can you put that in a new project, in a `deps.edn` file and run `clojure`? And then see what that does?

```
{:deps
 {selmer/selmer {:mvn/version "1.12.50"},
  org.clojure/clojure {:mvn/version "1.11.1"},
  org.clojure/tools.logging {:mvn/version "1.1.0"},
  insn/insn {:mvn/version "0.5.2"},
  org.clojure/tools.cli {:mvn/version "1.0.206"},
  org.babashka/babashka.impl.reify {:mvn/version "0.1.3"},
  rewrite-clj/rewrite-clj {:mvn/version "1.1.45"},
  babashka/babashka.core
  {:git/url "https://github.com/babashka/babashka.core",
   :git/sha "52a6037bd4b632bffffb04394fb4efd0cdab6b1e"},
  hiccup/hiccup {:mvn/version "2.0.0-alpha2"},
  org.babashka/cli {:mvn/version "0.3.35"},
  org.clojure/data.xml {:mvn/version "0.2.0-alpha6"},
  org.clojure/data.csv {:mvn/version "1.0.0"},
  com.taoensso/timbre {:mvn/version "5.2.1"},
  com.cognitect/transit-clj {:mvn/version "1.0.329"},
  babashka/babashka.curl {:mvn/version "0.1.1"},
  clj-commons/clj-yaml {:mvn/version "0.7.109"},
  org.clojure/core.rrb-vector {:mvn/version "0.1.2"},
  org.babashka/sci.impl.types {:mvn/version "0.0.2"},
  cheshire/cheshire {:mvn/version "5.11.0"},
  org.clojure/core.match {:mvn/version "1.0.0"},
  io.github.nextjournal/dejavu
  {:git/sha "3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5"},
  org.clojure/test.check {:mvn/version "1.1.1"},
  babashka/fs {:mvn/version "0.1.2"},
  org.clojure/data.priority-map {:mvn/version "1.1.0"},
  nrepl/bencode {:mvn/version "1.1.0"},
  org.clojure/core.async {:mvn/version "1.5.648"},
  http-kit/http-kit {:mvn/version "2.6.0-RC1"}}}
```

**Comment by rgkirch** [comment]
```
PS C:\Users\richie\clerk-debug> clojure
Cloning: https://github.com/babashka/babashka.core
Cloning: https://github.com/nextjournal/dejavu.git
Downloading: org/babashka/babashka.impl.reify/0.1.3/babashka.impl.reify-0.1.3.pom from clojars
Error building classpath. Cannot invoke "java.io.File.isAbsolute()" because "f" is null
java.lang.NullPointerException: Cannot invoke "java.io.File.isAbsolute()" because "f" is null
        at clojure.tools.deps.alpha.util.dir$canonicalize.invokeStatic(dir.clj:30)
        at clojure.tools.deps.alpha.extensions.deps$fn__1352.invokeStatic(deps.clj:32)
        at clojure.tools.deps.alpha.extensions.deps$fn__1352.invoke(deps.clj:32)
        at clojure.lang.MultiFn.invoke(MultiFn.java:244)
        at clojure.tools.deps.alpha$expand_deps$children_task__746$fn__748$fn__749.invoke(alpha.clj:406)
        at clojure.tools.deps.alpha.util.concurrent$submit_task$task__479.invoke(concurrent.clj:34)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
PS C:\Users\richie\clerk-debug> ls


    Directory: C:\Users\richie\clerk-debug


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/12/2022   4:33 PM           1477 deps.edn


PS C:\Users\richie\clerk-debug> cat .\deps.edn
{:deps
 {selmer/selmer {:mvn/version "1.12.50"},
  org.clojure/clojure {:mvn/version "1.11.1"},
  org.clojure/tools.logging {:mvn/version "1.1.0"},
  insn/insn {:mvn/version "0.5.2"},
  org.clojure/tools.cli {:mvn/version "1.0.206"},
  org.babashka/babashka.impl.reify {:mvn/version "0.1.3"},
  rewrite-clj/rewrite-clj {:mvn/version "1.1.45"},
  babashka/babashka.core
  {:git/url "https://github.com/babashka/babashka.core",
   :git/sha "52a6037bd4b632bffffb04394fb4efd0cdab6b1e"},
  hiccup/hiccup {:mvn/version "2.0.0-alpha2"},
  org.babashka/cli {:mvn/version "0.3.35"},
  org.clojure/data.xml {:mvn/version "0.2.0-alpha6"},
  org.clojure/data.csv {:mvn/version "1.0.0"},
  com.taoensso/timbre {:mvn/version "5.2.1"},
  com.cognitect/transit-clj {:mvn/version "1.0.329"},
  babashka/babashka.curl {:mvn/version "0.1.1"},
  clj-commons/clj-yaml {:mvn/version "0.7.109"},
  org.clojure/core.rrb-vector {:mvn/version "0.1.2"},
  org.babashka/sci.impl.types {:mvn/version "0.0.2"},
  cheshire/cheshire {:mvn/version "5.11.0"},
  org.clojure/core.match {:mvn/version "1.0.0"},
  io.github.nextjournal/dejavu
  {:git/sha "3c4cf5e4dda3648e0d4c575a3433d19c511dd3e5"},
  org.clojure/test.check {:mvn/version "1.1.1"},
  babashka/fs {:mvn/version "0.1.2"},
  org.clojure/data.priority-map {:mvn/version "1.1.0"},
  nrepl/bencode {:mvn/version "1.1.0"},
  org.clojure/core.async {:mvn/version "1.5.648"},
  http-kit/http-kit {:mvn/version "2.6.0-RC1"}}}
```

**Comment by rgkirch** [comment]
```
java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
I'll try with 11 instead of 16.

**Comment by borkdude** [comment]
Which version of `clojure` is this? Perhaps try upgrading? Perhaps a file permission error?

**Comment by rgkirch** [comment]
That too.
```
clojure --version
Clojure CLI version 1.10.3.981
```

**Comment by rgkirch** [comment]
I [reinstalled clojure](https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows#install) and installed [java 11](https://adoptium.net/temurin/releases/?version=11).
```
PS C:\Users\richie> clojure --version
Clojure CLI version 1.11.1.1113
```
```
PS C:\Users\richie> java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)
```
It's failing whenever it sees `:git/url` and `:git/sha`.
e.g.
```
{:deps
 {com.taoensso/timbre {:git/url "https://github.com/ptaoussanis/timbre"
                       :git/sha "4223bac204669d9a98bf8b6db17f57d5f3e206e2"}}}
```
gives 
```
Cloning: https://github.com/ptaoussanis/timbre
Error building classpath. Commit not found for com.taoensso/timbre in repo https://github.com/ptaoussanis/timbre at 4223bac204669d9a98bf8b6db17f57d5f3e206e2
```
I don't know what to do about it but it's not an issue with clerk.

**Comment by rgkirch** [comment]
I tried deps too but had the same issue.
```
PowerShell -Command "iwr -useb https://raw.githubusercontent.com/borkdude/deps.clj/master/install.ps1 | iex"
```
from [here](https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows#questions)
```
PS C:\Users\richie\clerk-debug> deps
Clojure tools not yet in expected location: C:\Users\richie\.deps.clj\1.11.1.1155\ClojureTools\clojure-tools-1.11.1.1155.jar
Downloading https://download.clojure.org/install/clojure-tools-1.11.1.1155.zip to C:\Users\richie\.deps.clj\1.11.1.1155\ClojureTools
Successfully installed clojure tools!
Error building classpath. Commit not found for babashka/babashka.core in repo https://github.com/babashka/babashka.core at 52a6037bd4b632bffffb04394fb4efd0cdab6b1e
```

**Comment by borkdude** [comment]
At this point, I would try ask.clojure.org or the Slack channels: clj-on-windows / tools-deps

**Comment by rgkirch** [comment]
Thanks!
