### ISSUE TITLE
Latest Clerk markdown rendering breaks with custom JS

### ISSUE THREAD

**Issue by sritchie** [nextjournal/clerk#374]
This is on version 5cf3982b29c25a6fe70ee4d4444293c5320ff697.

Here is a full repro: https://github.com/sritchie/clerk-repro

On trying to render this index: https://github.com/sritchie/clerk-repro/blob/main/src/mathbox/examples/index.md

I am seeing nothing on the screen, and this in the logs:

```
index.js:173 Uncaught TypeError: Cannot read properties of null (reading 'start')
    at isAnimationControls (index.js:173:10)
    at isControllingVariants (index.js:174:34)
    at getCurrentTreeVariants (index.js:178:18)
    at useCreateMotionContext (index.js:233:17)
    at index.js:343:17
    at renderWithHooks (react-dom.development.js:16313:5)
    at updateForwardRef (react-dom.development.js:19250:66)
    at beginWork (react-dom.development.js:21647:38)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4122:25)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:4224:29)
isAnimationControls @ index.js:173
isControllingVariants @ index.js:174
getCurrentTreeVariants @ index.js:178
useCreateMotionContext @ index.js:233
(anonymous) @ index.js:343
renderWithHooks @ react-dom.development.js:16313
updateForwardRef @ react-dom.development.js:19250
beginWork @ react-dom.development.js:21647
callCallback @ react-dom.development.js:4122
invokeGuardedCallbackImpl @ react-dom.development.js:4224
invokeGuardedCallback @ react-dom.development.js:4475
beginWork$1 @ react-dom.development.js:27622
performUnitOfWork @ react-dom.development.js:26594
workLoopSync @ react-dom.development.js:26565
renderRootSync @ react-dom.development.js:26541
performConcurrentWorkOnRoot @ react-dom.development.js:26497
flushWork @ scheduler.development.js:240
performWorkUntilDeadline @ scheduler.development.js:575
```

**Comment by mk** [comment]
Hi @sritchie, thanks for the report. I've verified that the problem goes away if I downgrade `framer-motion` in https://github.com/sritchie/clerk-repro and have fixed the version in the attached commit.
